/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  Fragment,
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type { Call } from "@hovoh/ethcall";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../common";

export interface RebalancerManagerInterface extends utils.Interface {
  functions: {
    "HARVESTER_ROLE()": FunctionFragment;
    "HOUSE_KEEPER_ROLE()": FunctionFragment;
    "LIQUIDATOR_ROLE()": FunctionFragment;
    "PAUSER_ROLE()": FunctionFragment;
    "REBALANCER_ROLE()": FunctionFragment;
    "UNPAUSER_ROLE()": FunctionFragment;
    "allowExecutor(address,bool)": FunctionFragment;
    "allowedExecutor(address)": FunctionFragment;
    "chief()": FunctionFragment;
    "completeRebalance(address,uint256,uint256,address,address,address,bool)": FunctionFragment;
    "rebalanceVault(address,uint256,uint256,address,address,address,bool)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "HARVESTER_ROLE"
      | "HOUSE_KEEPER_ROLE"
      | "LIQUIDATOR_ROLE"
      | "PAUSER_ROLE"
      | "REBALANCER_ROLE"
      | "UNPAUSER_ROLE"
      | "allowExecutor"
      | "allowedExecutor"
      | "chief"
      | "completeRebalance"
      | "rebalanceVault"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "HARVESTER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "HOUSE_KEEPER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LIQUIDATOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PAUSER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "REBALANCER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "UNPAUSER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "allowExecutor",
    values: [string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "allowedExecutor",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "chief", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "completeRebalance",
    values: [
      string,
      BigNumberish,
      BigNumberish,
      string,
      string,
      string,
      boolean
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "rebalanceVault",
    values: [
      string,
      BigNumberish,
      BigNumberish,
      string,
      string,
      string,
      boolean
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "HARVESTER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "HOUSE_KEEPER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LIQUIDATOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PAUSER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "REBALANCER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "UNPAUSER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "allowExecutor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "allowedExecutor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "chief", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "completeRebalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rebalanceVault",
    data: BytesLike
  ): Result;

  events: {
    "AllowExecutor(address,bool)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AllowExecutor"): EventFragment;
}

export interface AllowExecutorEventObject {
  executor: string;
  allowed: boolean;
}
export type AllowExecutorEvent = TypedEvent<
  [string, boolean],
  AllowExecutorEventObject
>;

export type AllowExecutorEventFilter = TypedEventFilter<AllowExecutorEvent>;

export interface RebalancerManager extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: RebalancerManagerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    HARVESTER_ROLE(overrides?: CallOverrides): Promise<[string]>;

    HOUSE_KEEPER_ROLE(overrides?: CallOverrides): Promise<[string]>;

    LIQUIDATOR_ROLE(overrides?: CallOverrides): Promise<[string]>;

    PAUSER_ROLE(overrides?: CallOverrides): Promise<[string]>;

    REBALANCER_ROLE(overrides?: CallOverrides): Promise<[string]>;

    UNPAUSER_ROLE(overrides?: CallOverrides): Promise<[string]>;

    allowExecutor(
      executor: string,
      allowed: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    allowedExecutor(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    chief(overrides?: CallOverrides): Promise<[string]>;

    completeRebalance(
      vault: string,
      assets: BigNumberish,
      debt: BigNumberish,
      from: string,
      to: string,
      flasher: string,
      setToAsActiveProvider: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    rebalanceVault(
      vault: string,
      assets: BigNumberish,
      debt: BigNumberish,
      from: string,
      to: string,
      flasher: string,
      setToAsActiveProvider: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  HARVESTER_ROLE(overrides?: CallOverrides): Promise<string>;

  HOUSE_KEEPER_ROLE(overrides?: CallOverrides): Promise<string>;

  LIQUIDATOR_ROLE(overrides?: CallOverrides): Promise<string>;

  PAUSER_ROLE(overrides?: CallOverrides): Promise<string>;

  REBALANCER_ROLE(overrides?: CallOverrides): Promise<string>;

  UNPAUSER_ROLE(overrides?: CallOverrides): Promise<string>;

  allowExecutor(
    executor: string,
    allowed: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  allowedExecutor(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  chief(overrides?: CallOverrides): Promise<string>;

  completeRebalance(
    vault: string,
    assets: BigNumberish,
    debt: BigNumberish,
    from: string,
    to: string,
    flasher: string,
    setToAsActiveProvider: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  rebalanceVault(
    vault: string,
    assets: BigNumberish,
    debt: BigNumberish,
    from: string,
    to: string,
    flasher: string,
    setToAsActiveProvider: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    HARVESTER_ROLE(overrides?: CallOverrides): Promise<string>;

    HOUSE_KEEPER_ROLE(overrides?: CallOverrides): Promise<string>;

    LIQUIDATOR_ROLE(overrides?: CallOverrides): Promise<string>;

    PAUSER_ROLE(overrides?: CallOverrides): Promise<string>;

    REBALANCER_ROLE(overrides?: CallOverrides): Promise<string>;

    UNPAUSER_ROLE(overrides?: CallOverrides): Promise<string>;

    allowExecutor(
      executor: string,
      allowed: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    allowedExecutor(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    chief(overrides?: CallOverrides): Promise<string>;

    completeRebalance(
      vault: string,
      assets: BigNumberish,
      debt: BigNumberish,
      from: string,
      to: string,
      flasher: string,
      setToAsActiveProvider: boolean,
      overrides?: CallOverrides
    ): Promise<boolean>;

    rebalanceVault(
      vault: string,
      assets: BigNumberish,
      debt: BigNumberish,
      from: string,
      to: string,
      flasher: string,
      setToAsActiveProvider: boolean,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {
    "AllowExecutor(address,bool)"(
      executor?: string | null,
      allowed?: null
    ): AllowExecutorEventFilter;
    AllowExecutor(
      executor?: string | null,
      allowed?: null
    ): AllowExecutorEventFilter;
  };

  estimateGas: {
    HARVESTER_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    HOUSE_KEEPER_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    LIQUIDATOR_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    PAUSER_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    REBALANCER_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    UNPAUSER_ROLE(overrides?: CallOverrides): Promise<BigNumber>;

    allowExecutor(
      executor: string,
      allowed: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    allowedExecutor(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    chief(overrides?: CallOverrides): Promise<BigNumber>;

    completeRebalance(
      vault: string,
      assets: BigNumberish,
      debt: BigNumberish,
      from: string,
      to: string,
      flasher: string,
      setToAsActiveProvider: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    rebalanceVault(
      vault: string,
      assets: BigNumberish,
      debt: BigNumberish,
      from: string,
      to: string,
      flasher: string,
      setToAsActiveProvider: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    HARVESTER_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    HOUSE_KEEPER_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    LIQUIDATOR_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    PAUSER_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    REBALANCER_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    UNPAUSER_ROLE(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    allowExecutor(
      executor: string,
      allowed: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    allowedExecutor(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    chief(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    completeRebalance(
      vault: string,
      assets: BigNumberish,
      debt: BigNumberish,
      from: string,
      to: string,
      flasher: string,
      setToAsActiveProvider: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    rebalanceVault(
      vault: string,
      assets: BigNumberish,
      debt: BigNumberish,
      from: string,
      to: string,
      flasher: string,
      setToAsActiveProvider: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}

export interface RebalancerManagerMulticall {
  address: string;
  abi: Fragment[];
  functions: FunctionFragment[];

  HARVESTER_ROLE(overrides?: CallOverrides): Call<string>;

  HOUSE_KEEPER_ROLE(overrides?: CallOverrides): Call<string>;

  LIQUIDATOR_ROLE(overrides?: CallOverrides): Call<string>;

  PAUSER_ROLE(overrides?: CallOverrides): Call<string>;

  REBALANCER_ROLE(overrides?: CallOverrides): Call<string>;

  UNPAUSER_ROLE(overrides?: CallOverrides): Call<string>;

  allowedExecutor(arg0: string, overrides?: CallOverrides): Call<boolean>;

  chief(overrides?: CallOverrides): Call<string>;
}
