/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type { Provider } from "@ethersproject/providers";
import { Contract, Signer, utils } from "ethers";
import type {
  IFlasher,
  IFlasherInterface,
  IFlasherMulticall,
} from "../../../src/interfaces/IFlasher";
import { Contract as MulticallContract } from "@hovoh/ethcall";
const _abi = [
  {
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "asset",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "amount",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "router",
            type: "address",
          },
          {
            internalType: "enum IRouter.Action[]",
            name: "actions",
            type: "uint8[]",
          },
          {
            internalType: "bytes[]",
            name: "args",
            type: "bytes[]",
          },
        ],
        internalType: "struct IFlasher.FlashloanParams",
        name: "params",
        type: "tuple",
      },
      {
        internalType: "uint8",
        name: "providerId",
        type: "uint8",
      },
    ],
    name: "initiateFlashloan",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
export class IFlasher__factory {
  static readonly abi = _abi;
  static createInterface(): IFlasherInterface {
    return new utils.Interface(_abi) as IFlasherInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IFlasher {
    return new Contract(address, _abi, signerOrProvider) as IFlasher;
  }
  static multicall(address: string): IFlasherMulticall {
    return new MulticallContract(address, _abi) as unknown as IFlasherMulticall;
  }
}
