/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IFujiOracle,
  IFujiOracleInterface,
} from "../../../src/interfaces/IFujiOracle";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "newPriceFeedAddress",
        type: "address",
      },
    ],
    name: "AssetPriceFeedChanged",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_collateralAsset",
        type: "address",
      },
      {
        internalType: "address",
        name: "_borrowAsset",
        type: "address",
      },
      {
        internalType: "uint8",
        name: "_decimals",
        type: "uint8",
      },
    ],
    name: "getPriceOf",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IFujiOracle__factory {
  static readonly abi = _abi;
  static createInterface(): IFujiOracleInterface {
    return new utils.Interface(_abi) as IFujiOracleInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IFujiOracle {
    return new Contract(address, _abi, signerOrProvider) as IFujiOracle;
  }
}
