/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IBeefyUniV2ZapVelodrome__factory } from "./IBeefyUniV2ZapVelodrome__factory";
export { IBeefyVaultV6__factory } from "./IBeefyVaultV6__factory";
