/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type { Provider } from "@ethersproject/providers";
import { Contract, Signer, utils } from "ethers";
import type {
  IComptroller,
  IComptrollerInterface,
  IComptrollerMulticall,
} from "../../../../src/interfaces/compoundV2/IComptroller";
import { Contract as MulticallContract } from "@hovoh/ethcall";
const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "holder",
        type: "address",
      },
    ],
    name: "claimComp",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address[]",
        name: "",
        type: "address[]",
      },
    ],
    name: "enterMarkets",
    outputs: [
      {
        internalType: "uint256[]",
        name: "",
        type: "uint256[]",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "cyTokenAddress",
        type: "address",
      },
    ],
    name: "exitMarket",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];
export class IComptroller__factory {
  static readonly abi = _abi;
  static createInterface(): IComptrollerInterface {
    return new utils.Interface(_abi) as IComptrollerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IComptroller {
    return new Contract(address, _abi, signerOrProvider) as IComptroller;
  }
  static multicall(address: string): IComptrollerMulticall {
    return new MulticallContract(
      address,
      _abi
    ) as unknown as IComptrollerMulticall;
  }
}
