[profile.default]
solc = "0.8.15"
src = 'src'
out = 'out'
libs = ['lib']
fs_permissions = [
  { access = "read-write", path = "./.local" },
  { access = "read-write", path = "./deployments" },
  { access = "read", path = "./deploy-configs" },
  { access = "read", path = "./out" }
]
optimizer = true
optimizer_runs = 200
build_info = true
extra_output = ["storageLayout"]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[rpc_endpoints]
mainnet = "${RPC_MAINNET}"
ethereum = "${RPC_MAINNET}"
goerli = "${RPC_GOERLI}"
optimism_goerli = "${RPC_OPTIMISM_GOERLI}"
optimism = "${RPC_OPTIMISM}"
mumbai = "${RPC_MUMBAI}"
polygon = "${RPC_POLYGON}"
arbitrum = "${RPC_ARBITRUM}"
gnosis = "${RPC_GNOSIS}"

[etherscan]
mainnet = { key = "${ETHERSCAN_KEY}" }
ethereum = { key = "${ETHERSCAN_KEY}" }
goerli =  { key = "${ETHERSCAN_KEY}" }
optimism_goerli = { key = "${OPTIMISM_ETHERSCAN_KEY}" }
optimism = { key = "${OPTIMISM_ETHERSCAN_KEY}" }
mumbai = { key = "${POLYGON_ETHERSCAN_KEY}" }
polygon = { key = "${POLYGON_ETHERSCAN_KEY}" }
arbitrum = { key = "${ARBITRUM_ETHERSCAN_KEY}" }
gnosis = { key = "${GNOSIS_ETHERSCAN_KEY}" }

[fmt]
line_length = 100
tab_width = 2
bracket_spacing = false
multiline_func_header = "all"
