/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IVelodromePair } from "./IVelodromePair";
export type { IVelodromeRouter } from "./IVelodromeRouter";
