/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IWETH9__factory } from "./IWETH9__factory";
export { PeripheryPayments__factory } from "./PeripheryPayments__factory";
