/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as goerli from "./goerli";
export type { goerli };
import type * as rinkeby from "./rinkeby";
export type { rinkeby };
