/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as borrowing from "./borrowing";
export type { borrowing };
export type { VaultPermissions } from "./VaultPermissions";
