/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AaveV3Optimism__factory } from "./AaveV3Optimism__factory";
export { BeefyVelodromesETHETH__factory } from "./BeefyVelodromesETHETH__factory";
