/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AaveV3Goerli } from "./AaveV3Goerli";
export type { CompoundV2Goerli } from "./CompoundV2Goerli";
