/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type { Provider } from "@ethersproject/providers";
import { Contract, Signer, utils } from "ethers";
import type {
  MockAddrMapper,
  MockAddrMapperInterface,
  MockAddrMapperMulticall,
} from "../../../src/mocks/MockAddrMapper";
import { Contract as MulticallContract } from "@hovoh/ethcall";
const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address[]",
        name: "keyAddress",
        type: "address[]",
      },
      {
        indexed: false,
        internalType: "address",
        name: "mappedAddress",
        type: "address",
      },
    ],
    name: "MappingChanged",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "providerName",
        type: "string",
      },
      {
        internalType: "address",
        name: "inputAddr",
        type: "address",
      },
    ],
    name: "getAddressMapping",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "providerName",
        type: "string",
      },
      {
        internalType: "address",
        name: "inputAddr1",
        type: "address",
      },
      {
        internalType: "address",
        name: "inputAddr2",
        type: "address",
      },
    ],
    name: "getAddressNestedMapping",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getProviders",
    outputs: [
      {
        internalType: "string[]",
        name: "",
        type: "string[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "prepareToRedeploythisAddress",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "renounceOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "providerName",
        type: "string",
      },
      {
        internalType: "address",
        name: "keyAddr",
        type: "address",
      },
      {
        internalType: "address",
        name: "returnedAddr",
        type: "address",
      },
    ],
    name: "setMapping",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "providerName",
        type: "string",
      },
      {
        internalType: "address",
        name: "keyAddr1",
        type: "address",
      },
      {
        internalType: "address",
        name: "keyAddr2",
        type: "address",
      },
      {
        internalType: "address",
        name: "returnedAddr",
        type: "address",
      },
    ],
    name: "setNestedMapping",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
export class MockAddrMapper__factory {
  static readonly abi = _abi;
  static createInterface(): MockAddrMapperInterface {
    return new utils.Interface(_abi) as MockAddrMapperInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): MockAddrMapper {
    return new Contract(address, _abi, signerOrProvider) as MockAddrMapper;
  }
  static multicall(address: string): MockAddrMapperMulticall {
    return new MulticallContract(
      address,
      _abi
    ) as unknown as MockAddrMapperMulticall;
  }
}
