/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import type { Provider } from "@ethersproject/providers";
import { Contract, Signer, utils } from "ethers";
import type {
  ICallback,
  ICallbackInterface,
  ICallbackMulticall,
} from "../../../../../../../../../../lib/nxtp/packages/deployments/contracts/contracts/core/promise/interfaces/ICallback";
import { Contract as MulticallContract } from "@hovoh/ethcall";
const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "transferId",
        type: "bytes32",
      },
      {
        internalType: "bool",
        name: "success",
        type: "bool",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "callback",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
export class ICallback__factory {
  static readonly abi = _abi;
  static createInterface(): ICallbackInterface {
    return new utils.Interface(_abi) as ICallbackInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ICallback {
    return new Contract(address, _abi, signerOrProvider) as ICallback;
  }
  static multicall(address: string): ICallbackMulticall {
    return new MulticallContract(
      address,
      _abi
    ) as unknown as ICallbackMulticall;
  }
}
