/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export declare namespace LibSigUtils {
  export type PermitStruct = {
    owner: PromiseOrValue<string>;
    spender: PromiseOrValue<string>;
    amount: PromiseOrValue<BigNumberish>;
    nonce: PromiseOrValue<BigNumberish>;
    deadline: PromiseOrValue<BigNumberish>;
  };

  export type PermitStructOutput = [
    string,
    string,
    BigNumber,
    BigNumber,
    BigNumber
  ] & {
    owner: string;
    spender: string;
    amount: BigNumber;
    nonce: BigNumber;
    deadline: BigNumber;
  };
}

export interface LibSigUtilsInterface extends utils.Interface {
  functions: {
    "getHashTypedDataV4Digest(bytes32,bytes32)": FunctionFragment;
    "getStructHashAsset((address,address,uint256,uint256,uint256))": FunctionFragment;
    "getStructHashBorrow((address,address,uint256,uint256,uint256))": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "getHashTypedDataV4Digest"
      | "getStructHashAsset"
      | "getStructHashBorrow"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getHashTypedDataV4Digest",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "getStructHashAsset",
    values: [LibSigUtils.PermitStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "getStructHashBorrow",
    values: [LibSigUtils.PermitStruct]
  ): string;

  decodeFunctionResult(
    functionFragment: "getHashTypedDataV4Digest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStructHashAsset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStructHashBorrow",
    data: BytesLike
  ): Result;

  events: {};
}

export interface LibSigUtils extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: LibSigUtilsInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getHashTypedDataV4Digest(
      domainSeperator: PromiseOrValue<BytesLike>,
      structHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getStructHashAsset(
      permit: LibSigUtils.PermitStruct,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getStructHashBorrow(
      permit: LibSigUtils.PermitStruct,
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  getHashTypedDataV4Digest(
    domainSeperator: PromiseOrValue<BytesLike>,
    structHash: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<string>;

  getStructHashAsset(
    permit: LibSigUtils.PermitStruct,
    overrides?: CallOverrides
  ): Promise<string>;

  getStructHashBorrow(
    permit: LibSigUtils.PermitStruct,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    getHashTypedDataV4Digest(
      domainSeperator: PromiseOrValue<BytesLike>,
      structHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    getStructHashAsset(
      permit: LibSigUtils.PermitStruct,
      overrides?: CallOverrides
    ): Promise<string>;

    getStructHashBorrow(
      permit: LibSigUtils.PermitStruct,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    getHashTypedDataV4Digest(
      domainSeperator: PromiseOrValue<BytesLike>,
      structHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getStructHashAsset(
      permit: LibSigUtils.PermitStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getStructHashBorrow(
      permit: LibSigUtils.PermitStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getHashTypedDataV4Digest(
      domainSeperator: PromiseOrValue<BytesLike>,
      structHash: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getStructHashAsset(
      permit: LibSigUtils.PermitStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getStructHashBorrow(
      permit: LibSigUtils.PermitStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
