/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { Fragment, FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type { Call } from "@hovoh/ethcall";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../common";

export declare namespace LibSigUtils {
  export type PermitStruct = {
    chainid: BigNumberish;
    owner: string;
    operator: string;
    receiver: string;
    amount: BigNumberish;
    nonce: BigNumberish;
    deadline: BigNumberish;
  };

  export type PermitStructOutput = [
    BigNumber,
    string,
    string,
    string,
    BigNumber,
    BigNumber,
    BigNumber
  ] & {
    chainid: BigNumber;
    owner: string;
    operator: string;
    receiver: string;
    amount: BigNumber;
    nonce: BigNumber;
    deadline: BigNumber;
  };
}

export interface LibSigUtilsInterface extends utils.Interface {
  functions: {
    "buildPermitStruct(address,address,address,uint256,uint256,address)": FunctionFragment;
    "getHashTypedDataV4Digest(bytes32,bytes32)": FunctionFragment;
    "getStructHashAsset((uint256,address,address,address,uint256,uint256,uint256))": FunctionFragment;
    "getStructHashBorrow((uint256,address,address,address,uint256,uint256,uint256))": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "buildPermitStruct"
      | "getHashTypedDataV4Digest"
      | "getStructHashAsset"
      | "getStructHashBorrow"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "buildPermitStruct",
    values: [string, string, string, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getHashTypedDataV4Digest",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getStructHashAsset",
    values: [LibSigUtils.PermitStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "getStructHashBorrow",
    values: [LibSigUtils.PermitStruct]
  ): string;

  decodeFunctionResult(
    functionFragment: "buildPermitStruct",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getHashTypedDataV4Digest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStructHashAsset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStructHashBorrow",
    data: BytesLike
  ): Result;

  events: {};
}

export interface LibSigUtils extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: LibSigUtilsInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    buildPermitStruct(
      owner: string,
      operator: string,
      receiver: string,
      amount: BigNumberish,
      plusNonce: BigNumberish,
      vault_: string,
      overrides?: CallOverrides
    ): Promise<
      [LibSigUtils.PermitStructOutput] & {
        permit: LibSigUtils.PermitStructOutput;
      }
    >;

    getHashTypedDataV4Digest(
      domainSeperator: BytesLike,
      structHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getStructHashAsset(
      permit: LibSigUtils.PermitStruct,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getStructHashBorrow(
      permit: LibSigUtils.PermitStruct,
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  buildPermitStruct(
    owner: string,
    operator: string,
    receiver: string,
    amount: BigNumberish,
    plusNonce: BigNumberish,
    vault_: string,
    overrides?: CallOverrides
  ): Promise<LibSigUtils.PermitStructOutput>;

  getHashTypedDataV4Digest(
    domainSeperator: BytesLike,
    structHash: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  getStructHashAsset(
    permit: LibSigUtils.PermitStruct,
    overrides?: CallOverrides
  ): Promise<string>;

  getStructHashBorrow(
    permit: LibSigUtils.PermitStruct,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    buildPermitStruct(
      owner: string,
      operator: string,
      receiver: string,
      amount: BigNumberish,
      plusNonce: BigNumberish,
      vault_: string,
      overrides?: CallOverrides
    ): Promise<LibSigUtils.PermitStructOutput>;

    getHashTypedDataV4Digest(
      domainSeperator: BytesLike,
      structHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    getStructHashAsset(
      permit: LibSigUtils.PermitStruct,
      overrides?: CallOverrides
    ): Promise<string>;

    getStructHashBorrow(
      permit: LibSigUtils.PermitStruct,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    buildPermitStruct(
      owner: string,
      operator: string,
      receiver: string,
      amount: BigNumberish,
      plusNonce: BigNumberish,
      vault_: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getHashTypedDataV4Digest(
      domainSeperator: BytesLike,
      structHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getStructHashAsset(
      permit: LibSigUtils.PermitStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getStructHashBorrow(
      permit: LibSigUtils.PermitStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    buildPermitStruct(
      owner: string,
      operator: string,
      receiver: string,
      amount: BigNumberish,
      plusNonce: BigNumberish,
      vault_: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getHashTypedDataV4Digest(
      domainSeperator: BytesLike,
      structHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getStructHashAsset(
      permit: LibSigUtils.PermitStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getStructHashBorrow(
      permit: LibSigUtils.PermitStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}

export interface LibSigUtilsMulticall {
  address: string;
  abi: Fragment[];
  functions: FunctionFragment[];

  buildPermitStruct(
    owner: string,
    operator: string,
    receiver: string,
    amount: BigNumberish,
    plusNonce: BigNumberish,
    vault_: string,
    overrides?: CallOverrides
  ): Call<LibSigUtils.PermitStructOutput>;

  getHashTypedDataV4Digest(
    domainSeperator: BytesLike,
    structHash: BytesLike,
    overrides?: CallOverrides
  ): Call<string>;

  getStructHashAsset(
    permit: LibSigUtils.PermitStruct,
    overrides?: CallOverrides
  ): Call<string>;

  getStructHashBorrow(
    permit: LibSigUtils.PermitStruct,
    overrides?: CallOverrides
  ): Call<string>;
}
