/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  LibSigUtils,
  LibSigUtilsInterface,
} from "../../../src/libraries/LibSigUtils";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "domainSeperator",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "structHash",
        type: "bytes32",
      },
    ],
    name: "getHashTypedDataV4Digest",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "owner",
            type: "address",
          },
          {
            internalType: "address",
            name: "spender",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "amount",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "nonce",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "deadline",
            type: "uint256",
          },
        ],
        internalType: "struct LibSigUtils.Permit",
        name: "permit",
        type: "tuple",
      },
    ],
    name: "getStructHashAsset",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "owner",
            type: "address",
          },
          {
            internalType: "address",
            name: "spender",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "amount",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "nonce",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "deadline",
            type: "uint256",
          },
        ],
        internalType: "struct LibSigUtils.Permit",
        name: "permit",
        type: "tuple",
      },
    ],
    name: "getStructHashBorrow",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
];

export class LibSigUtils__factory {
  static readonly abi = _abi;
  static createInterface(): LibSigUtilsInterface {
    return new utils.Interface(_abi) as LibSigUtilsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): LibSigUtils {
    return new Contract(address, _abi, signerOrProvider) as LibSigUtils;
  }
}
