/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IBeefyUniV2ZapVelodrome } from "./IBeefyUniV2ZapVelodrome";
export type { IBeefyVaultV6 } from "./IBeefyVaultV6";
