name: CI-Contracts

on:
  pull_request:
    branches:
      - main
    paths:
      - "packages/frontend/**"
  push:
    branches:
      - main
    paths:
      - "packages/frontend/**"
  
  # Allows you to run this workflow manually from the Actions tab      
  workflow_dispatch:

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  #lint:
    #name: Run Linters
    #runs-on: ubuntu-latest

    #strategy:
      #matrix:
        #node-version: [16.x]

    #steps:
      #- uses: actions/checkout@v3

      #- name: Install Foundry
        #uses: foundry-rs/foundry-toolchain@v1
        #with:
          #version: nightly

      #- name: Use Node.js
        #uses: actions/setup-node@v3
        #with:
          #node-version: ${{ matrix.node-version }}
          #cache: "yarn"

      #- run: yarn workspace @x-fuji/frontend install
      #- run: yarn workspace @x-fuji/frontend run lint
      #- run: yarn workspace @x-fuji/frontend run prettier --check

  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: 'ubuntu-latest'

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: 'actions/checkout@v3'

    - name: Use Node ${{ matrix.node }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}
        cache: "yarn"

    - name: Install deps and build (with cache)
      uses: bahmutov/npm-install@v1
      with:
        useLockFile: false
        working-directory: packages/frontend

    - name: Build
      run: yarn build
      working-directory: packages/frontend

    - uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: '${{ secrets.WIF_PROVIDER_NAME }}'
        service_account: '${{ secrets.APPENGINE_DEPLOY_SA_EMAIL }}'

    - id: 'deploy'
      name: 'deploy'
      uses: 'google-github-actions/deploy-appengine@v0'
      with:
        deliverables: 'packages/frontend/app.yaml'

    - name: 'show output'
      run: 'echo ${{ steps.deploy.outputs.url }}'
