name: CI-Sdk

on:
  pull_request:
    branches:
      - main
    paths:
      - "packages/sdk/**"
  push:
    branches:
      - main
    paths:
      - "packages/sdk/**"
  
  # Allows you to run this workflow manually from the Actions tab      
  workflow_dispatch:

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['14.x']
        os: [ubuntu-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1
        working-directory: ./packages/sdk

      - name: Lint
        run: yarn lint
        working-directory: ./packages/sdk

      - name: Test
        run: yarn test --ci --maxWorkers=2
        working-directory: ./packages/sdk

      - name: Build
        run: yarn build
        working-directory: ./packages/sdk
