name: CI-Sdk

on:
  pull_request:
    branches:
      - main
    paths:
      - "packages/sdk/**"
  push:
    branches:
      - main
    paths:
      - "packages/sdk/**"
  
  # Allows you to run this workflow manually from the Actions tab      
  workflow_dispatch:

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['14.x']
        os: [ubuntu-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: "yarn"

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1

      - name: Lint
        run: yarn sdk:lint

      - name: Test
        run: yarn sdk:test --ci --maxWorkers=2

      - name: Build
        run: yarn sdk:build
